language: node_js
rvm:
  - 2.0.0
node_js:
  - 0.10
before_install:
  - ruby --version
  - gem --version
  - gem install asciidoctor
  - gem install coderay
  - npm install -g gulp
script:
  - make test-all
after_success:
  - npm run-script deploy
env:
  global:
  - GH_REF: github.com/azu/Promises-book.git
  - secure: pNtiVeWTe/kPWmERJURFoCVfzDVOc19IPbr9rK9CDJHo9aFtBPXkRwYzXfjlIwnzzkrAnfowxNNerHxYXuiNK7z+xNT9H79pmYtd1Qap9fNZCFNIFkdaArAXoq635VWmGRdArGiQGNM4Am+bZdsgG4dJR4DEsjx6dcisfyb8yso=
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/02e67e9b440eddb4a3da
    on_success: change
    on_failure: always
    on_start: false