language: node_js
node_js:
- '0.10'
before_install:
- gem --version
- gem install asciidoctor
- gem install pygments.rb
after_success:
- npm run-script deploy
env:
  global:
  - GH_REF: github.com/azu/Promises-book.git
  - secure: pNtiVeWTe/kPWmERJURFoCVfzDVOc19IPbr9rK9CDJHo9aFtBPXkRwYzXfjlIwnzzkrAnfowxNNerHxYXuiNK7z+xNT9H79pmYtd1Qap9fNZCFNIFkdaArAXoq635VWmGRdArGiQGNM4Am+bZdsgG4dJR4DEsjx6dcisfyb8yso=
